#!/bin/sh

if [ $# -eq 0 ]
then
    echo "usage: $0 <command>"
    exit 1
fi

case $1 in
    "start")
        if [ $# -ne 3 ]
        then
            echo "$0: You must give chapter and problem number"
            exit 1
        else
            cp template.cc `printf "ch_%02d_%02d.cc" $2 $3`
            echo "Your input. Line by line." > `printf "ch_%02d_%02d.input" $2 $3`
        fi;;
    "run")
        if [ $# -ne 3 ]
        then
            echo "$0: You must give chapter and problem number"
            exit 1
        else
            g++ -std=c++11 `printf "ch_%02d_%02d.cc" $2 $3` && ./a.out < `printf "ch_%02d_%02d.input" $2 $3` && rm a.out > /dev/null
        fi;;
    *) echo "$0: Command not found";;
esac
